language: go
go:
- '1.10'
- master

before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
- dep ensure
deploy:
  provider: lambda
  function_name: "copilot-crawler"
  region: "us-east-1"
  role: "arn:aws:iam::254074152624:role/cloudformation_lambda"
  runtime: "go1.x"
  handler_name: "newGitRepo"
