AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: copilot-crawler lambda

Resources:
  CopilotGetNewRepoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./cmd/newGitRepo
      Handler: newGitRepo
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      KmsKeyArn: arn:aws:kms:us-east-1:254074152624:key/08da6af7-ffbc-4df1-a43c-bec2881b8325
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          GITHUB_TOKEN: AQICAHhzFFHkfn0L3z6ZGF/V2mW5kre/Tzky+mq/FphIgqRhxgFmm1q7FXRxhcX/KPvG/iQsAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFdMk35LrdPmw1/MmAIBEIBDhm2FHoxTJAY3MYU1oP2MT30gOd/8QdIhvo8eBSoTdM7j4jXg0/jfIESVI6HK/mVEH5RcI88nnfDSuou5sa+CsaUsDw==
      Events:
        NewCopilotRepo:
          Type: SNS
          Properties:
            Topic: aws:sns:us-east-1:254074152624:copilot-repo-new

